language: java
jdk: 
 - openjdk8

after_success:   
 - bash <(curl -s https://codecov.io/bash)
deploy:
 povider: script
 script: printf "\nRun release script \n"; mvn --version
 on:
  branch: master
  