server:
  port: 8080
  context-path: /cosmo
spring:
  application:
    name: cosmo-webapp
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true
    username: root
    password: '1234'
    driver-class-name: org.mariadb.jdbc.Driver
    

# Moved from etc/application.properties
cosmo:
  tikets: 
    serverSecret: cosmossecret
    serverInteger: 1235    
  hibernate:
     hibernatePackagesToScan: org.unitedinternet.cosmo.model.hibernate  
  caldav:   
     schedulingEnabled: true

# connection timeout for reaching external content when validation is performed (in millis) 
external:
  content:
    connection:
      timeout: 10000
    size: 1048576
    non:
      proxyed:
        hosts:  
calendar: 
  server:
   productId: COSMO
   