## TODO - Move to cosmo-webapp submodule.
server:
  port: 8080
  servlet:
    context-path: /cosmo
spring:
  application:
    name: cosmo-webapp
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/cosmo?autoReconnect=true
    username: cosmo
    password: '*'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10     
  jpa:        
    properties:
     hibernate.dialect: org.unitedinternet.cosmo.hibernate.CosmoMySQL5InnoDBDialect     
     hibernate.cache.use_query_cache: false
     hibernate.cache.use_second_level_cache: false
     hibernate.show_sql: false
     hibernate.hbm2ddl.auto: validate
     hibernate.id.new_generator_mappings: false
        